project_id = "lbeeodbqzcklosgvqyej"

[functions.initiate-payment]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.payment-success]
verify_jwt = false

[functions.send-delivery-email]
verify_jwt = false

[functions.download-ebook]
verify_jwt = false
